COOKIE_BANNER_MESSAGE = (
    "Używamy analitycznych plików cookie (GA4) do statystyk ruchu. "
    "Możesz je zaakceptować lub odrzucić."
)
COOKIE_ACCEPT_LABEL = "Akceptuję analitykę"
COOKIE_REJECT_LABEL = "Odrzucam"
COOKIE_SETTINGS_LABEL = "Zmień ustawienia cookies"
COOKIE_SETTINGS_ICON = "🍪"
PRIVACY_POLICY_LABEL = "Polityka prywatności"
PRIVACY_POLICY_ICON = "🔒"
PRIVACY_POLICY_TITLE = "Polityka prywatności"
PRIVACY_POLICY_CONTENT = (
    "Data wejścia w życie: 22.02.2026\n"
    "Data ostatniej aktualizacji: 22.02.2026\n\n"
    "1. Administrator danych osobowych\n"
    "Administratorem danych osobowych jest Koło Psychologiczne Studentów WAM działające przy Warszawskiej Akademii Medycznej Nauk Stosowanych, "
    "adres: Rydygiera 8, 01-793 Warszawa, e-mail: kontakt@psychowam.pl (dalej: \"Administrator\").\n"
    "Administrator nie wyznaczył Inspektora Ochrony Danych.\n\n"
    "2. Jakie dane zbieramy\n"
    "W związku z korzystaniem z serwisu www.psychowam.pl możemy przetwarzać:\n"
    "- dane podane dobrowolnie (np. imię, nazwisko, e-mail, treść wiadomości),\n"
    "- dane techniczne (np. adres IP, informacje o urządzeniu, logi serwera),\n"
    "- dane z plików cookies, w tym analityczne po wyrażeniu zgody.\n\n"
    "3. Cele i podstawa prawna przetwarzania\n"
    "Dane przetwarzamy w następujących celach:\n"
    "- kontakt i obsługa zapytań: art. 6 ust. 1 lit. f RODO (uzasadniony interes Administratora) lub art. 6 ust. 1 lit. b RODO,\n"
    "- organizacja działalności koła (np. zapisy/rekrutacja do działań): art. 6 ust. 1 lit. b lub f RODO,\n"
    "- newsletter/aktualności (jeśli prowadzony): art. 6 ust. 1 lit. a RODO (zgoda),\n"
    "- analiza ruchu przy użyciu Google Analytics 4: art. 6 ust. 1 lit. a RODO (zgoda na analityczne cookies),\n"
    "- zapewnienie bezpieczeństwa serwisu i przeciwdziałanie nadużyciom: art. 6 ust. 1 lit. f RODO.\n\n"
    "4. Pliki cookies\n"
    "Serwis korzysta z cookies niezbędnych do działania strony oraz cookies analitycznych (GA4).\n"
    "Cookies analityczne są uruchamiane wyłącznie po wyrażeniu zgody w banerze cookies.\n"
    "Zgodę można wycofać w dowolnym momencie przyciskiem ustawień cookies.\n\n"
    "5. Odbiorcy danych\n"
    "Dane mogą być przekazywane podmiotom wspierającym nas technicznie, w szczególności:\n"
    "- dostawcom hostingu i infrastruktury IT,\n"
    "- dostawcom narzędzi analitycznych (Google Analytics 4),\n"
    "- podmiotom świadczącym wsparcie techniczne.\n"
    "Dane nie są sprzedawane ani udostępniane w celach marketingowych podmiotów trzecich.\n\n"
    "6. Transfer danych poza EOG\n"
    "W związku z korzystaniem z usług Google dane mogą być przekazywane poza Europejski Obszar Gospodarczy.\n"
    "Transfer odbywa się z zastosowaniem mechanizmów zgodnych z RODO (np. standardowych klauzul umownych).\n\n"
    "7. Okres przechowywania danych\n"
    "Dane przechowujemy przez okres nie dłuższy niż niezbędny do realizacji celu przetwarzania.\n"
    "Dla Google Analytics 4 retencja jest ustawiona następująco:\n"
    "- dane zdarzeń: 2 miesiące,\n"
    "- dane użytkownika: 14 miesięcy.\n"
    "Po upływie okresów retencji dane są usuwane lub anonimizowane zgodnie z zasadami dostawcy usługi.\n\n"
    "8. Prawa użytkownika\n"
    "Przysługuje Ci prawo do:\n"
    "- dostępu do danych,\n"
    "- sprostowania danych,\n"
    "- usunięcia danych,\n"
    "- ograniczenia przetwarzania,\n"
    "- przenoszenia danych (gdy podstawą jest zgoda lub umowa),\n"
    "- sprzeciwu wobec przetwarzania,\n"
    "- cofnięcia zgody w dowolnym momencie,\n"
    "- wniesienia skargi do Prezesa Urzędu Ochrony Danych Osobowych (PUODO).\n\n"
    "9. Dobrowolność podania danych\n"
    "Podanie danych jest dobrowolne, ale w części przypadków niezbędne do skorzystania z określonych funkcji serwisu.\n\n"
    "10. Zmiany polityki prywatności\n"
    "Polityka prywatności może być aktualizowana. Aktualna wersja jest zawsze publikowana w serwisie.\n\n"
    "11. Kontakt\n"
    "W sprawach dotyczących prywatności: kontakt@psychowam.pl."
)
