"""Article short

Revision ID: 8621f864c085
Revises: f82a393eb353
Create Date: 2025-10-26 17:20:50.429648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8621f864c085'
down_revision = 'f82a393eb353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_content', sa.String(length=255), nullable=True))

    # Wypełnij kolumnę domyślną wartością
    op.execute("UPDATE article SET short_content = 'Brak opisu' WHERE short_content IS NULL;")

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('short_content', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('short_content')

    # ### end Alembic commands ###
