"""add username and phone

Revision ID: 90946aa25126
Revises: 8621f864c085
Create Date: 2026-02-14 13:43:50.590991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90946aa25126'
down_revision = '8621f864c085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('short_content',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('username')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('short_content',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
